
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Fiction','Fiction','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Classics','Books belong to a certain time period and they have literary merits','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Tragedy','The tragedy is a drama book that focuses on the sufferings and tragedies of humans.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Sci-Fi','Sci-Fi or science fiction is an umbrella term for types of books genres that have advanced concepts of science and technology.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Fantasy','These are the stories that revolve around magic, witchcraft, supernatural, mythical creatures, etc.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Crime & Mystery','These stories usually revolve around a crime from the moment it is committed to the time it is solved.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Romance','Romance stories often depict a loving relationship between two people.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Humor and Satire’s','Humor is a comedy work of fiction where the writer wants to amuse the readers and make them laugh with the narrative.','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Comics','The stories in comic books are represented by sequential and engaging narrative art with images and dialogues. ','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Children’s','Children’s','SYSTEM',CURRENT_TIMESTAMP());

INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Pride and Prejudice', 'Pride and Prejudice', ' Jane Austen', '9780141439518',30,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The tragedy of HAMLET, prince of Denmark', 'The tragedy of HAMLET, prince of Denmark', ' William Shakespeare', '979-8835906598', 90,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Project Hail Mary', 'Project Hail Mary', 'Andy Weir', '978-0593135204', 120,7, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Harry Potter Box Set Paperback', 'Harry Potter Box Set Paperback', 'J. K. Rowling', '978-3-16-148410-3', 120,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Sentinel: A Jack Reacher Novel', 'A Jack Reacher Novel', ' Lee Child', '1984818481', 150,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Silent Patient', 'The Silent Patient', 'Alex Michaelides', '978-1250301697', 100,4, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('It Ends With Us', 'It Ends With Us', 'Colleen Hoover', '1501110365', 160,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Animal Farm', '', 'George Orwell ', '978-3-16-131313-7', 110,7, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('If It Bleeds', 'If It Bleeds', 'Stephen King ', '978-3-16-148311-8', 115,7, 'SYSTEM',CURRENT_TIMESTAMP());


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('20SUMMER07','20% OFF ON Sci-Fi', 20, '2022-07-31 11:59:00');

INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('JAN15','15% OFF ON Comics', 10, '2022-03-30 11:59:00');


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('ALL25','25% OFF ON ALL BOOKS', 25, '2022-08-30 11:59:00');


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('ROMANCE30','30% OFF ON Romance BOOKS ', 30, '2022-07-30 11:59:00');


INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (1, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (1, 7);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (2, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (2, 7);

INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 2);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 3);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 4);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 5);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 6);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 7);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 8);

INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (4, 4);







